### ISSUE TITLE
Timeout implementation has many issues

### ISSUE THREAD

**Issue by Thomas-Haase** [david-maw/StreamSSL#18]
**Many** thanks for this code. I've successfully integrated the client part into my application. In this application we need correct timeout behaviour, so I did extensive tests regarding the timeout behaviour and end user friendly error message. Unfortunately your code has several issues in timeout context. It seems to me that your main focus was the complicated WSA API part (again, many thanks for this), but the timeout implementation has got obviously minor focus. Some of the timeour issues were recently reported at your code project site, I will not repeat this here.
But I would like to say that _Blonder_ is preparing a pull request with a significant better time out implementation, and I highly recommend to merge this pull request.

**Comment by david-maw** [comment]
Yep, based on your comments it looks like the timeout logic was pretty miserable, another error path bites the dust... You are right, I was mostly focused on the code to deal with SSL, TCP and certificate handling and it’s a source of amazement to me how faulty code like this can often exist unnoticed for a long time. I'll be happy to see an improvement, my only warning is to remember that it might take multiple receives (or, in theory, sends) to handle a whole SSL packet and the timeout should address the whole packet, not the individual receive/send calls, since the application caller has no control over these. Unless you can simulate a network that fragments packets it can be difficult to test this scenario.

There's no doubt this code would benefit from some test cases. Also, I'd like to win the lottery...

**Comment by david-maw** [comment]
I think I've cleaned up all the issues and added a bit of functionality to deal with using ReadPartial when encryption is not on (so the data arrives in a stream not discrete chunks).

The timer granularity is still seconds though, do you need of finer granularity?

**Comment by Thomas-Haase** [comment]
Thanks. I had milliseconds before, but in the meantime I have migrated my source code to seconds. For me, seconds are fine enough.
One chunk, that sounds like a good idea.

**Comment by david-maw** [comment]
ok, I left it at seconds. I think the merged functionality in BaseSock is correct now.
