### ISSUE TITLE
CActiveSock should be derived public from CBaseSock instead of private

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#57]
else I can't access the ActualSocket member of the CBaseSock class any more - I use a class derived from CActiveSock that needs access to ActualSocket

**Comment by david-maw** [comment]
Inheriting private was a deliberate choice because I did not want to expose the other protected members of CBaseSock to classes that inherited from CActiveSock / CPassiveSock. I've explicitly made ActualSocket and m_hStopEvent inheritable protected from CActiveSock / CPassiveSock, hopefully that'll solve your problem.
