### ISSUE TITLE
The project should contain a LICENSE file

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#69]
as e.g. in https://github.com/google/googletest

**Comment by david-maw** [comment]
I thought it was enough that the ReadMe.md says it is licensed under the CPOL (CodeProject Open License) and provides a URL to it. What else do you think is needed? I don't object to providing something if it would help, just need to know what and why.

**Comment by Blonder** [comment]
A lot of libraries that I use contain a LICENSE file e.g. utfcpp, utf8proc, Info-ZIP zip/unzip, ..., if the user is interested in the license he only needs to look into this file - it's obvious where to look, if it's in the readme, he needs to search for the relevant section.

**Comment by david-maw** [comment]
ok, I'm always wary of taking snapshots of licenses, since they have a tendency to evolve over time in response to changes in law or interpretation. Still, this license is meant to be very simple, basically "use what you like, in any way you like, just don't hold me responsible for errors", so I put a snapshot in "License.htm" and updated the readme.md to say that.
