### ISSUE TITLE
The License file seems to have a problem...

### ISSUE THREAD

**Issue by Blonder** [david-maw/StreamSSL#74]
it is not shown formatted when clicking on "View License" in GitHub, there is a ? in front of `<html>`, maybe this is the problem.

**Comment by david-maw** [comment]
The "?" certainly does not seem right, so I deleted it. GitHub still seems to list the html rather than rendering it though, which seems odd - maybe it can only handle text or markdown formatted licenses. Anyway, I verified that chrome, IE and Edge can all render the license file, so I think the html is legal now.

**Comment by david-maw** [comment]
Converting the license file from HTML to markdown seems to have done the trick, GitHub now renders it correctly.
