### ISSUE TITLE
Version number shown on codeproject is different than on github

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [david-maw/StreamSSL#88]
codeproject February 2019 - release 2.1.1
 - https://www.codeproject.com/Articles/1000189/A-Working-TCP-Client-and-Server-With-SSL
 
github 2.1.0 
 - https://github.com/david-maw/StreamSSL/releases 
 
 Are you planning to release a 2.1.1 with the issue https://github.com/david-maw/StreamSSL/issues/86 fixed?

**Comment by david-maw** [comment]
Yes, I'm just slooow. Now the source is in GitHub I should figure out how to put sample object files there for people who just want to try it out then I could just redirect from CodeProject to GitHub and I just have not had time to sort all that out yet.

The version situation is trickier than it looks, as the master branch history in Git indicates, there were already versions labelled 2.1.1 and 2.1.2 (and 2.1.2 is the current one)  but appversion.h in 2.1.2 still says 2.1.1 and of course there's nothing that Github recognizes as a release. So, it all works, but the versioning is a mess and needs some time devoted to fixing it.

If an official release this is something you need urgently, just let me know, otherwise it'll just wait until it rises to the top of my "to do" pile.

**Comment by Andreas-Schniertshauer** [comment]
Thanks for clarifying this - no I don't need it urgently, I only wanted to inform you about the differences.

**Comment by david-maw** [comment]
Thanks, I appreciate the information, originally I maintained the code locally and just pushed periodic updates to CodeProject, then I realized GitHub would be a better home for the source files so I moved them there and (eventually) started defining releases. Evidently I have not made the the GitHub and CodeProject data as consistent as I should have, but I expect all it'll take to do that is being able to dedicate a few uninterrupted hours.

**Comment by david-maw** [comment]
I think it's corrected, I didn't push 2.1.2 back to code project because it's such a minor change, but 2.1.1 and 2.1.2 now show up correctly as releases in GitHub.
